### ISSUE TITLE
Auto Delete function

### ISSUE THREAD

**Issue by AndreasW4** [kylefortin/WarlockUtilities#2]
Hi, Is the Autodelete function working as intended when i get a popup after each fight when i loot. that needs me to press the "autodelete" button for it to delete? 

I have been to interface -> addon and enabled autodelete, ask it to save 2 and delete the rest. been trying with both the bag option and number option. 

Best regards!

**Comment by kylefortin** [comment]
The AutoDelete function uses the Blizzard `DeleteCursorItem` function to delete inventory items (soul shards), which is protected and must be triggered from a button press.  The current logic should show the popup with the AutoDelete button whenever your inventory changes (i.e. looting any item) and the number of soul shards you have exceeds the threshold (in this case, sounds like 2).  Pressing the button should delete all soul shards except the first two in your bags.

**Comment by AndreasW4** [comment]
ahh, I see. Thank you for the reply. is there any way i can trigger the "autodelete" in a macro?
Then i can set the number i want to keep and bind it to a hotkey. or even macro it togheter with a spell i use often. 

Best regards

**Comment by kylefortin** [comment]
Can create a macro with the following line.  Note that this can be run at any time, but will only delete shards when out of combat lockdown.

/script _G["WU"]:ExecuteAutoDelete();

**Comment by AndreasW4** [comment]
Perfect! Thank you very much!

Have a nice evening!

Best regards Andreas
