### ISSUE TITLE
Warlockutilities move

### ISSUE THREAD

**Issue by hellrider81** [kylefortin/WarlockUtilities#4]
Hi Kyle!

How can i move the Appbar?
I have no configuration for it!

Regards Albert

**Comment by kylefortin** [comment]
1st would double check to make sure you are using v2.1.0 or higher (support for moving the App Tray was added in that patch). Can then access settings via the `/wu config` command, and go to the App Tray tab to choose a screen side to dock to, and an offset from center of that side.  Can reference https://github.com/kylefortin/WarlockUtilities/blob/master/ReadMe/AppTray.md
