### ISSUE TITLE
Compatibility issues with bagnon - Escape input ignored ?

### ISSUE THREAD

**Issue by AlexDev-9000** [kylefortin/WarlockUtilities#6]
Heya ! thanks for the addon, it looks cool, just a small list of issues I've found:
- Autodelete and Shard manager do not seem to be compatible with Bagnon. The AutoDelete popup only shows if triggering a Bagnon's "clean items" function: 
![image](https://github.com/kylefortin/WarlockUtilities/assets/25059191/26074f7a-9920-4c1d-821b-934b0fef2748)

Even then, the AutoDelete function does not work, clicking the button does nothing:

![image](https://github.com/kylefortin/WarlockUtilities/assets/25059191/6f7c663e-fc33-4558-a7a0-9840799c5515)

Similarly, none of the functions of the shard manager seem to work. 

-Esc does not work to close open menus. I don't know if it's by design, but I prefer to use esc to close menus, and the mod seems to be ignoring this unput completly.

**Comment by kylefortin** [comment]
Appreciate the feedback, previously this did work with Bagnon. Unfortunately this addon is no longer being actively maintained, I will mark the repo as archived and update the readme.
